plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - MPLABFirstSteps/MPLAB_First_Steps.md
  - PIC32CMLS00CuriosityNanoDocumentation/PIC32_nano_docs.md